# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true # Doesn't work anymore due to https://jekyllrb.com/docs/upgrading/2-to-3/#relative-permalink-support-removed

# Setup
title:               Teststation
tagline:             'Order from Chaos'
description: > # this means to ignore newlines until "baseurl:"
  Hello, welcome to my blog :-) I don't say much but I occasionally write
  about things I've learned from a variety of sources, just to be able to
  refer to them myself later. Feel free to look around and get in touch.
url:                 https://blog.teststation.org/
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Rohit Shriwas
  url:               https://rohit.teststation.org/
  email:             rohit@teststation.org

# Custom vars
version:             1.0.0

# Paginator gem
gems: [jekyll-paginate]
